name: Run CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: sudo apt-get install -y xmlstarlet

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Variables
      run: |
        # echo "branch=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
        # echo "package=$(xmlstarlet sel -t -v '/package/metadata/id' Pelias.NET.nuspec)" >> $GITHUB_ENV
        echo "version=$(xmlstarlet sel -t -v '/package/metadata/version' Pelias.NET.nuspec).${{ github.run_number }}" >> $GITHUB_ENV

    - name: Update Package Version
      run: xmlstarlet ed --inplace -u "/package/metadata/version" -v "${{ env.version }}" Pelias.NET.nuspec

    - name: Build Package
      run: dotnet build --configuration Release -p:PackageVersion=${{ env.version }}

    - name: Test Package
      run: dotnet test --configuration Release --no-build

    - name: Pack Package
      run: dotnet pack --configuration Release -p:PackageVersion=${{ env.version }}

    - name: Pack Publish
      run: dotnet publish --configuration Release -p:PackageVersion=${{ env.version }} -o build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release.zip
        path: |
          Pelias.NET.nuspec
          README.md
          ./build/*.nupkg
        if-no-files-found: error
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Create Tarball
      run: tar -czf v${{ env.version }}.tar.gz ./build/*
   
    - name: Create Zip
      run: zip -jr v${{ env.version }}.zip ./build/*
   
    - name: Create Zip Release
      run: gh release create v${{ env.version }} './v${{ env.version }}.tar.gz#Binaries (tar.gz)' './v${{ env.version }}.zip#Binaries (zip)'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    #if: github.event_name == 'release'

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: release.zip
  
    - name: Publish to NuGet
      run: dotnet nuget push ./build/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.TOKEN_NUGET }}
